branch-defaults:
  master:
    environment: localing-api-dev
    group_suffix: null
global:
  application_name: localing-api
  branch: null
  default_ec2_keyname: null
  default_platform: Docker
  default_region: eu-west-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
