openapi: 3.0.1
info:
  title: api
  description: Localing API
  version: 1.0.0
servers:
  - url: /api/v1
tags:
  - name: Business, Products, Orders
    description: Endpoints for businesses, products and orders
  - name: Specification
    description: The swagger API specification

paths:
  /business:
    get:
      tags:
        - Business
      description: Fetch all businesses
      responses:
        200:
          description: Return all businesses
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Business'
        4XX:
          description: Business not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        5XX:
          description: Business not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /business/{id}:
    get:
      tags:
        - Business
      parameters:
        - name: id
          in: path
          description: The id of the business to retrieve
          required: true
          schema:
            type: string
      responses:
        200:
          description: Return the business with the specified id
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Business'
        4XX:
          description: Business not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        5XX:
          description: Business not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /product:
    get:
      tags:
        - Product
      description: Fetch all products
      responses:
        200:
          description: Return all products
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
        4XX:
          description: Product not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        5XX:
          description: Product not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /product/{id}:
    get:
      tags:
        - Product
      parameters:
        - name: id
          in: path
          description: The id of the product to retrieve
          required: true
          schema:
            type: string
      responses:
        200:
          description: Return the product with the specified id
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        4XX:
          description: Product not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        5XX:
          description: Product not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /spec:
    get:
      tags:
        - Specification
      responses:
        200:
          description: Return the API specification
          content: {}
components:
  schemas:
    
    Business:
      type: object
      properties:
        businessId:
          type: string
        paymentAccountId:
          type: string
        email:
          type: string
        active:
          type: string
        name: 
          type: string
        description:
          type: string
        categories:
          type: array
          items:
            type: string
        latitude:
          type: number
        longitude:
          type: number
        area:
          type: string
        address:
          type: string
        imageURL:
          type: string
        website:
          type: string
        phone:
          type: string

    Product:
      type: object
      properties:
          active:
            type: boolean
          businessId:
            type: string
          currency:
            type: string
          description:
            type: string
          images:
            type: array
            items:
              type: string
          name:
            type: string
          price:
            type: number
          productId:
            type: string


    Error:
      type: object
      additionalProperties: true