name: Deploy Staging to Elastic Beanstalk
on:
  push:
    branches:
    - staging

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout source code
      uses: actions/checkout@v1

    - name: Generate deployment package
      run: zip -r deploy.zip . -x '*.git*'

    - name: Generate build number
      id: buildnumber
      uses: einaregilsson/build-number@v2 
      with:
        token: ${{secrets.github_token}} 
      
    - name: Deploy to EB
      uses: einaregilsson/beanstalk-deploy@v11
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: localing-api
        environment_name: localing-api-staging
        region: eu-west-1
        version_label: ${{ steps.buildnumber.outputs.build_number }}
        deployment_package: deploy.zip
